clients:
  tblclients:
    columns:
      company:
        formatter: company
      vat:
        formatter: vat
      phonenumber:
        formatter: phoneNumber
      city:
        formatter: city
      zip:
        formatter: postcode
      state:
        delete: true
      address:
        formatter: streetAddress
      website:
        delete: true
      billing_street:
        formatter: streetAddress
      billing_city:
        formatter: city
      billing_zip:
        formatter: postcode
      billing_state:
        delete: true
      billing_country:
        formatter: country
      shipping_street:
        formatter: streetAddress
      shipping_city:
        formatter: city
      shipping_zip:
        formatter: postcode
      shipping_state:
        delete: true
      shipping_country:
        formatter: country
