contacts:
  tblcontacts:
    columns:
      firstname:
        formatter: firstname
      lastname:
        formatter: lastname
      email:
        formatter: email
      phonenumber:
        formatter: phoneNumber
      title:
        formatter: company
