newsletter_recipient:
    newsletter_recipient: { email: { formatter: email }, first_name: { formatter: first_name }, last_name: { formatter: last_name }, city: { formatter: city }, street: { formatter: street } }
