order_address:
    order_address: { company: { formatter: company }, first_name: { formatter: first_name }, last_name: { formatter: last_name }, street: { formatter: street }, zipcode: { formatter: zipcode }, city: { formatter: city }, phone_number: { formatter: phone } }
